"""Human-readable class names for the road sign dataset."""


CLASS_NAME_RU = {
    "prio_priority_road": "Главная дорога",
    "prio_give_way": "Уступите дорогу",
    "prio_stop": "Стоп",
    "forb_ahead": "Движение прямо запрещено",
    "forb_left": "Поворот налево запрещён",
    "forb_right": "Поворот направо запрещён",
    "forb_overtake": "Обгон запрещён",
    "forb_speed_over_5": "Ограничение скорости 5 км/ч",
    "forb_speed_over_10": "Ограничение скорости 10 км/ч",
    "forb_speed_over_20": "Ограничение скорости 20 км/ч",
    "forb_speed_over_30": "Ограничение скорости 30 км/ч",
    "forb_speed_over_40": "Ограничение скорости 40 км/ч",
    "forb_speed_over_50": "Ограничение скорости 50 км/ч",
    "forb_speed_over_60": "Ограничение скорости 60 км/ч",
    "forb_speed_over_70": "Ограничение скорости 70 км/ч",
    "forb_speed_over_80": "Ограничение скорости 80 км/ч",
    "forb_speed_over_90": "Ограничение скорости 90 км/ч",
    "forb_speed_over_100": "Ограничение скорости 100 км/ч",
    "forb_speed_over_130": "Ограничение скорости 130 км/ч",
    "forb_stopping": "Остановка запрещена",
    "forb_trucks": "Движение грузовиков запрещено",
    "forb_u_turn": "Разворот запрещён",
    "forb_weight_over_3.5t": "Ограничение массы 3,5 т",
    "forb_weight_over_7.5t": "Ограничение массы 7,5 т",
    "info_crosswalk": "Пешеходный переход",
    "info_highway": "Автомагистраль",
    "info_one_way_traffic": "Одностороннее движение",
    "warn_crosswalk": "Предупреждение о пешеходном переходе",
    "info_taxi_parking": "Стоянка такси",
    "mand_bike_lane": "Велосипедная дорожка",
    "mand_right": "Движение направо",
    "mand_left": "Движение налево",
    "mand_left_right": "Движение налево или направо",
    "mand_pass_left": "Объезд слева",
    "mand_pass_right": "Объезд справа",
    "mand_pass_left_right": "Объезд слева или справа",
    "mand_straigh_left": "Движение прямо или налево",
    "mand_straight_left": "Движение прямо или налево",
    "mand_straight": "Движение прямо",
    "mand_straight_right": "Движение прямо или направо",
    "mand_roundabout": "Круговое движение",
    "info_parking": "Парковка",
    "info_bus_station": "Автобусная остановка",
    "warn_children": "Дети",
    "warn_traffic_light": "Светофор",
    "warn_cyclists": "Велосипедисты",
    "warn_construction": "Дорожные работы",
    "warn_other_dangers": "Прочие опасности",
    "warn_poor_road_surface": "Неровная дорога",
    "warn_roundabout": "Предупреждение о круговом движении",
    "warn_slippery_road": "Скользкая дорога",
    "warn_speed_bumper": "Искусственная неровность",
    "warn_tram": "Трамвай",
    "warn_two_way_traffic": "Двустороннее движение",
    "warn_wild_animals": "Дикие животные",
    "warn_domestic_animals": "Домашние животные",
}


def get_display_class_name(class_name: str) -> str:
    """Return a Russian class name when known."""
    return CLASS_NAME_RU.get(class_name, class_name.replace("_", " ").capitalize())
